-- VIEWS SRH E SSA
GRANT SELECT ON SSA.USUARIO_SISTEMA TO RL_BLOQ_PRV;
/
GRANT SELECT ON SSA.USUARIO_APLICACAO_CLASSE TO RL_BLOQ_PRV;
/

GRANT SELECT ON SRH.IS_VW_FUNCIONARIO TO BLOQ WITH GRANT OPTION;
/
GRANT SELECT ON SRH.IS_VW_FUNCIONARIO TO RL_BLOQ_PRV;
/
CREATE OR REPLACE VIEW BLOQ.IE_VW_FUNCIONARIO AS
SELECT *
FROM SRH.IS_VW_FUNCIONARIO FNC
WITH READ ONLY;
/
GRANT SELECT ON BLOQ.IE_VW_FUNCIONARIO TO RL_BLOQ_PRV;
/
GRANT SELECT ON BLOQ.IE_VW_FUNCIONARIO TO BLOQ_WEB;
/

GRANT SELECT ON SSA.VW_USUARIO_EXT_ACESS_ESP TO BLOQ WITH GRANT OPTION;
/
GRANT SELECT ON SSA.VW_USUARIO_EXT_ACESS_ESP TO RL_BLOQ_PRV;
/
CREATE OR REPLACE VIEW BLOQ.IE_SSA_VW_USUARIO_EXTERNO AS
SELECT *
  FROM SSA.VW_USUARIO_EXT_ACESS_ESP
WITH READ ONLY;
/
GRANT SELECT ON BLOQ.IE_SSA_VW_USUARIO_EXTERNO TO RL_BLOQ_PRV;
/
GRANT SELECT ON BLOQ.IE_SSA_VW_USUARIO_EXTERNO TO BLOQ_WEB;
/

-- BLOQUEIO SSA 
GRANT EXECUTE ON SSA.IS_PK_SSA_BLOQUEAR TO BLOQ WITH GRANT OPTION;
/
GRANT EXECUTE ON SSA.IS_PK_SSA_BLOQUEAR TO RL_BLOQ_PRV;
/
CREATE OR REPLACE PACKAGE BLOQ.IE_PK_SSA_BLOQUEAR IS
 FUNCTION FC_BLOQUEIO_SSA(P_NU_CPF IN NUMBER, P_MSG OUT VARCHAR2) RETURN NUMBER;
END IE_PK_SSA_BLOQUEAR;
/
CREATE OR REPLACE PACKAGE BODY BLOQ.IE_PK_SSA_BLOQUEAR IS
  FUNCTION FC_BLOQUEIO_SSA(P_NU_CPF IN NUMBER, P_MSG OUT VARCHAR2) RETURN NUMBER IS CODERR NUMBER;
  V_RETORNO_1 NUMBER;
  V_RETORNO_2 NUMBER;
  BEGIN
     V_RETORNO_1:= SSA.IS_PK_SSA_BLOQUEAR.FC_DESABILITA_USR_SSA(P_NU_CPF, P_MSG);
     V_RETORNO_2:= SSA.IS_PK_SSA_BLOQUEAR.FC_DESABILITA_USR_SSA(P_NU_CPF, P_MSG);

    IF (V_RETORNO_1=0 AND
        V_RETORNO_2=0)
    THEN
      CODERR:=0;
      P_MSG:='Usuário desabilitado com sucesso no SSA';
      RETURN(CODERR);

    ELSIF ((V_RETORNO_1=1 AND V_RETORNO_2=1) OR
           (V_RETORNO_1=0 AND V_RETORNO_2=1) OR
           (V_RETORNO_1=1 AND V_RETORNO_2=0)
           )
    THEN
           CODERR:=1;
           P_MSG := 'Usuário inexistente no SSA';
           RETURN(CODERR);

    ELSIF ((V_RETORNO_1=2 AND V_RETORNO_2=2) OR
           (V_RETORNO_1=2 AND V_RETORNO_2=1) OR
           (V_RETORNO_1=2 AND V_RETORNO_2=0) OR
           (V_RETORNO_1=1 AND V_RETORNO_2=2) OR
           (V_RETORNO_1=0 AND V_RETORNO_2=2)
           )
    
  THEN 
           CODERR:=2;
           P_MSG :='Erro ao desabilitar o usuário cpf ' || p_nu_cpf || ' no SSA';
           RETURN(CODERR);
    END IF;

    EXCEPTION
    WHEN OTHERS THEN
      CODERR := 2;
      P_MSG :='Erro ao desabilitar o usuário cpf ' || p_nu_cpf || ' no SSA';
      RETURN(CODERR);

  END;
END IE_PK_SSA_BLOQUEAR;
/
GRANT EXECUTE ON BLOQ.IE_PK_SSA_BLOQUEAR TO RL_BLOQ_PRV;
/
GRANT EXECUTE ON BLOQ.IE_PK_SSA_BLOQUEAR TO BLOQ_WEB;
/
