-- BLOQUEIO SIAFE
GRANT EXECUTE ON SIAFE_RIO.IS_SIAFE_BLOQUEAR_USUARIO  TO BLOQ WITH GRANT OPTION;
/
GRANT EXECUTE ON SIAFE_RIO.IS_SIAFE_BLOQUEAR_USUARIO  TO RL_BLOQ_PRV;
/
CREATE OR REPLACE FUNCTION BLOQ.IE_SIAFE_FC_BLOQUEAR(P_NUM_CPF IN NUMBER, P_MSG OUT VARCHAR2) RETURN NUMBER IS CODERR NUMBER;
V_TXT_CPF VARCHAR2(11); 
V_RETORNO NUMBER;
BEGIN

   V_TXT_CPF := TO_CHAR(NVL(P_NUM_CPF,'0'));
   
   IF LENGTH(V_TXT_CPF)<11
   THEN 
     V_TXT_CPF := LPAD(V_TXT_CPF, 11,'0');
   END IF;
      
   SIAFE_RIO.IS_SIAFE_BLOQUEAR_USUARIO(V_TXT_CPF, V_RETORNO, P_MSG);
   CODERR:=V_RETORNO;
   RETURN(CODERR);

    EXCEPTION
    WHEN OTHERS THEN
      CODERR := 2;
      P_MSG :='Erro ao desabilitar o usuário cpf ' || P_NUM_CPF || ' no SIAFERIO';
      RETURN(CODERR);

END IE_SIAFE_FC_BLOQUEAR;
/
  
GRANT EXECUTE ON BLOQ.IE_SIAFE_FC_BLOQUEAR TO RL_BLOQ_PRV;
/
GRANT EXECUTE ON BLOQ.IE_SIAFE_FC_BLOQUEAR TO BLOQ_WEB;
/
